---
title: "Assignment 2 QMM"
author: "Karthik Badiganti"
date: "2022-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Weigelt Problem

$$ \text{Objective is to Maximise:}\hspace{0.2cm}Z=420(L_1 + L_2+ L_3) + 360 (M_1 + M_2 + M_3) + 300 (S_1 + S_2 + S_3)\\
\text{subject to:}\\
L_1+M_1+S_1 \le 750 \\
L_2+M_2+S_2 \le 900 \\
L_3+M_3+S_3 \le 450\\
20L_1+15M_1+12S_1 \le 13000\\
20L_2+15M_2+12S_2 \le 12000\\
20L_3+15M_3+12S_3 \le 5000\\
L_1+L_2+L_3 \le 900 \\
M_1+M_2+M_3 \le 1200\\
S_1+S_2+S_3 \le 750\\
\text{Non Negativity:}\hspace{0.2cm}L_1,L_2,L_3,M_1,M_2,M_3,S_1,S_2,S_3 \ge 0
$$

$$\text{The above inequality equations can be written as:}\\
L_1+M_1+S_1+0L_2+0M_2+0S_2+0L_3+0M_3+0S_3 \le 750 \\
0L_1+0M_1+0S_1+L_2+M_2+S_2+0L_3+0M_3+0S_3 \le 900 \\
0L_1+0M_1+0S_1+0L_2+0M_2+0S_2+L_3+M_3+S_3 \le 450\\
20L_1+15M_1+12S_1+0L_2+0M_2+0S_2+0L_3+0M_3+0S_3 \le 13000\\
0L_1+0M_1+0S_1+20L_2+15M_2+12S_2+0L_3+0M_3+0S_3 \le 12000\\
0L_1+0M_1+0S_1+0L_2+0M_2+0S_2+20L_3+15M_3+12S_3 \le 5000\\
L_1+0M_1+0S_1+L_2+0M_2+0S_2+L_3+0M_3+0S_3 \le 900 \\
0L_1+M_1+0S_1+0L_2+M_2+0S_2+0L_3+M_3+0S_3 \le 1200\\
0L_1+0M_1+S_1+0L_2+0M_2+S_2+0L_3+0M_3+S_3 \le 750\\
$$

## Solving Using R for weigelt problem

```{r Weigelt}
require(lpSolve)
library(lpSolve)
f.obj<-c(420,360,300,420,360,300,420,360,300)
f.con<-matrix(c(1,1,1,0,0,0,0,0,0,
                0,0,0,1,1,1,0,0,0,
                0,0,0,0,0,0,1,1,1,
                20,15,12,0,0,0,0,0,0,
                0,0,0,20,15,12,0,0,0,
                0,0,0,0,0,0,20,15,12,
                1,0,0,1,0,0,1,0,0,
                0,1,0,0,1,0,0,1,0,
                0,0,1,0,0,1,0,0,1),nrow = 9, byrow=TRUE)
f.dir<-c('<=','<=','<=','<=','<=','<=','<=','<=','<=')
f.rhs<-c(750,900,450,13000,12000,5000,900,1200,750)
##SOlution for problem 2
lp('max',f.obj,f.con,f.dir,f.rhs)
cat('Solution for Weigelt problem is:',lp('max',f.obj,f.con,f.dir,f.rhs)$solution)
```

## Problem 2

$$\text{Objective is to Maximise:}\hspace{0.2cm} Z=3X_1 + 5X_2\\
\text{Subject to:}\\
X_1 \le 4\\
2X_2 \le 12\\
3X_1+2X_2 \le 18\\
\text{Non negativity:}\hspace{0.2cm} X_1,X_2 \ge 0$$

$$\text{The above inequality equations can be written as:}\\
X_1+0X_2 \le 4\\
0X_1+2X_2 \le 12\\
3X_1+2X_2 \le 18$$

## Solving Using R for Problem 2

```{r Problem 2}
require(lpSolve)
library(lpSolve)
f.obj<-c(3,5)
f.con<-matrix(c(1,0,
                0,2,
                3,2),nrow = 3, byrow=TRUE)
f.dir<-c('<=','<=','<=')
f.rhs<-c(4,12,18)
##SOlution for problem 2
lp('max',f.obj,f.con,f.dir,f.rhs)
cat('Solution for Weigelt problem is:',lp('max',f.obj,f.con,f.dir,f.rhs)$solution)
```
