---
title: "Assignment_3_QMM"
author: "Karthik Badiganti"
date: "2022-10-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Loading Packages
```{r packages}
library("lpSolveAPI")
library("lpSolve")
library("tinytex")
```


## Creating Table as per given data
```{r table creation}
cost <- matrix(c(22,14,30,600,100,
                 16,20,24,625,120,
                 80,60,70,"-","-"), ncol=5,byrow=T)

colnames(cost) <- c("Warehouse 1", "Warehouse 2", "Warehouse 3", "Production Cost", "Production Capacity")

rownames(cost) <- c("Plant A", "Plant B", "Demand")

cost <- as.table(cost)
cost

```  
## Formulation of Primal

$$ \text{The Objective Function is to Minimize the Transportation cost}$$

$$ Z = 622X_{11} + 614X_{12} + 630X_{13}  + 641X_{21} + 645X_{22} + 649X_{23}$$
 $$\text{Subject to:}
 $$

$$\text {Supply Constraints:}$$
$$X_{11} + X_{12} + X_{13} + X_{14} \le 100$$
$$X_{21} + X_{22} + X_{23} + X_{24} \le 120$$
$$\text {Demand Constraints}$$
$$X_{11} + X_{21}\ge 80$$
$$X_{12} + X_{22} \ge 60$$
$$X_{13} + X_{23} \ge 70$$

$${\text  Non - Negativity \hspace{2mm} Constraints} $$
$$X_{ij} >= 0 \hspace{4mm} \text {Where i = 1,2 for Plants A,B and j = 1,2,3 for Warehouses} $$
$$\text{Since demand is not equal to supply we are adding dummy variable for solving the equation}$$
# Solving Primal using R
```{r }
#Creating a matrix for the given objective function
costs <- matrix(c(622,614,630,0,
                 641,645,649,0), ncol=4, byrow=T)

#Defining the column names and row names
colnames(costs) <- c("Warehouse 1", "Warehouse 2", "Warehouse 3", "Dummy")

rownames(costs) <- c("Plant A", "Plant B")

costs
  
#Defining the row signs and row values based on above constraints
row.signs <- rep("<=",2)
row.rhs <- c(100,120)


#Defining the column signs and column values based on above constraints
col.signs <- rep(">=",4)
col.rhs <- c(80,60,70,10)



```
```{r lp solution}
#Running the lp.transport function 
trans.cost <- lp.transport(costs,"min", row.signs,row.rhs,col.signs,col.rhs)

#Getting the objective value
print(paste("The solution of primal is ",trans.cost$objval))


trans.cost$solution

```
$$\text{From the above results we can say that 132790 is the minimal cost obtained with}$$
$$ X_{12}=60$$
$$X_{13}=40$$
$$X_{21}=80$$
$$X_{23}=30$$

$$\text{Since the primal was to minimize the transportation cost the dual of it would be to maximize the value added(VA)}$$

$$ \text{ Maximize VA = }  100P_A + 120P_B - 80W_1 - 60W_2 - 70W_3$$

$$\text{Subject to the following constraints:}$$

$$ \text {Total Payments Constraints:} $$
$$ W_1 - P_A \ge 622 $$
$$ W_2 - P_A \ge 614$$
$$ W_3 - P_A \ge 630$$
$$ W_1 - P_B \ge 641$$
$$ W_2 - P_2 \ge 645$$
$$ W_3 - P_B \ge 649$$
$$W_i>0, \hspace{2mm}P_{j}>0 $$
$$ \text{Where i=1,2,3 are Total payments at destination Warehouses}$$
$$ \text{j=A,B are Total payments at Origin plants} $$